import 'package:flutter/material.dart';

void main() {
  runApp(const CAQuestApp());
  }

  class CAQuestApp extends StatelessWidget {
    const CAQuestApp({super.key});

      @override
        Widget build(BuildContext context) {
            return MaterialApp(
                  debugShowCheckedModeBanner: false,
                        title: 'CA Quest',
                              theme: ThemeData(
                                      brightness: Brightness.dark,
                                              primarySwatch: Colors.deepPurple,
                                                    ),
                                                          home: const SplashScreen(),
                                                              );
                                                                }
                                                                }

                                                                class SplashScreen extends StatelessWidget {
                                                                  const SplashScreen({super.key});

                                                                    @override
                                                                      Widget build(BuildContext context) {
                                                                          return Scaffold(
                                                                                backgroundColor: Colors.black,
                                                                                      body: Center(
                                                                                              child: Column(
                                                                                                        mainAxisAlignment: MainAxisAlignment.center,
                                                                                                                  children: [
                                                                                                                              const Icon(
                                                                                                                                            Icons.account_balance,
                                                                                                                                                          size: 90,
                                                                                                                                                                        color: Colors.amber,
                                                                                                                                                                                    ),
                                                                                                                                                                                                const SizedBox(height: 20),
                                                                                                                                                                                                            const Text(
                                                                                                                                                                                                                          "CA Quest",
                                                                                                                                                                                                                                        style: TextStyle(
                                                                                                                                                                                                                                                        fontSize: 32,
                                                                                                                                                                                                                                                                        fontWeight: FontWeight.bold,
                                                                                                                                                                                                                                                                                        color: Colors.white,
                                                                                                                                                                                                                                                                                                      ),
                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                              const SizedBox(height: 10),
                                                                                                                                                                                                                                                                                                                                          const Text(
                                                                                                                                                                                                                                                                                                                                                        "The Ledger of Destiny",
                                                                                                                                                                                                                                                                                                                                                                      style: TextStyle(
                                                                                                                                                                                                                                                                                                                                                                                      fontSize: 16,
                                                                                                                                                                                                                                                                                                                                                                                                      color: Colors.grey,
                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                                                                                                            const SizedBox(height: 40),
                                                                                                                                                                                                                                                                                                                                                                                                                                                        ElevatedButton(
                                                                                                                                                                                                                                                                                                                                                                                                                                                            onPressed: () {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Navigator.push(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        context,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          MaterialPageRoute(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              builder: (context) => const LevelScreen(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            child: const Text("Start Journey"),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      class LevelScreen extends StatelessWidget {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const LevelScreen({super.key});

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          @override
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Widget build(BuildContext context) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return Scaffold(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      appBar: AppBar(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              title: const Text("Foundation Level"),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          body: Center(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  child: Text(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "Debit = Credit\nPuzzle coming soon 🔥",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      textAlign: TextAlign.center,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                style: const TextStyle(fontSize: 22),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }