import 'dart:math';
import 'package:flutter/material.dart';

void main() {
  runApp(const CALudoApp());
  }

  class CALudoApp extends StatelessWidget {
    const CALudoApp({super.key});

      @override
        Widget build(BuildContext context) {
            return MaterialApp(
                  debugShowCheckedModeBanner: false,
                        theme: ThemeData.dark(),
                              home: const CALudoHome(),
                                  );
                                    }
                                    }

                                    class CALudoHome extends StatefulWidget {
                                      const CALudoHome({super.key});

                                        @override
                                          State<CALudoHome> createState() => _CALudoHomeState();
                                          }

                                          class _CALudoHomeState extends State<CALudoHome> {
                                            int dice = 1;
                                              int position = 0;
                                                String message = "Roll the Audit Dice 🎲";

                                                  final int totalSteps = 20;

                                                    void rollDice() {
                                                        final rnd = Random();
                                                            setState(() {
                                                                  dice = rnd.nextInt(6) + 1;

                                                                        // CA Rule
                                                                              if (dice == 6) {
                                                                                      message = "🎯 Audit Success! Answer CA question to move.";
                                                                                              // For now auto-allow (placeholder)
                                                                                                      position += dice;
                                                                                                            } else {
                                                                                                                    position += dice;
                                                                                                                            message = "Moved $dice steps";
                                                                                                                                  }

                                                                                                                                        if (position >= totalSteps) {
                                                                                                                                                position = totalSteps;
                                                                                                                                                        message = "🎓 CONGRATULATIONS! You are a CA!";
                                                                                                                                                              }
                                                                                                                                                                  });
                                                                                                                                                                    }

                                                                                                                                                                      Widget buildBoard() {
                                                                                                                                                                          return GridView.builder(
                                                                                                                                                                                shrinkWrap: true,
                                                                                                                                                                                      gridDelegate:
                                                                                                                                                                                                const SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount: 5),
                                                                                                                                                                                                      itemCount: totalSteps + 1,
                                                                                                                                                                                                            itemBuilder: (context, index) {
                                                                                                                                                                                                                    bool isPawn = index == position;
                                                                                                                                                                                                                            return Container(
                                                                                                                                                                                                                                      margin: const EdgeInsets.all(4),
                                                                                                                                                                                                                                                decoration: BoxDecoration(
                                                                                                                                                                                                                                                            color: isPawn ? Colors.amber : Colors.blueGrey.shade800,
                                                                                                                                                                                                                                                                        borderRadius: BorderRadius.circular(8),
                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                            child: Center(
                                                                                                                                                                                                                                                                                                        child: Text(
                                                                                                                                                                                                                                                                                                                      index == totalSteps ? "CA 🎓" : index.toString(),
                                                                                                                                                                                                                                                                                                                                    style: const TextStyle(fontWeight: FontWeight.bold),
                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                        },
                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                @override
                                                                                                                                                                                                                                                                                                                                                                                  Widget build(BuildContext context) {
                                                                                                                                                                                                                                                                                                                                                                                      return Scaffold(
                                                                                                                                                                                                                                                                                                                                                                                            appBar: AppBar(
                                                                                                                                                                                                                                                                                                                                                                                                    title: const Text("CA LUDO – The Board of Balance"),
                                                                                                                                                                                                                                                                                                                                                                                                            centerTitle: true,
                                                                                                                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                                                                                                        body: Padding(
                                                                                                                                                                                                                                                                                                                                                                                                                                padding: const EdgeInsets.all(12),
                                                                                                                                                                                                                                                                                                                                                                                                                                        child: Column(
                                                                                                                                                                                                                                                                                                                                                                                                                                                  children: [
                                                                                                                                                                                                                                                                                                                                                                                                                                                              const SizedBox(height: 10),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Text(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        message,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      textAlign: TextAlign.center,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    style: const TextStyle(fontSize: 18),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const SizedBox(height: 10),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Text(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      "Dice: $dice",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    style: const TextStyle(fontSize: 22),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const SizedBox(height: 10),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ElevatedButton(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onPressed: position < totalSteps ? rollDice : null,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    child: const Text("ROLL AUDIT DICE 🎲"),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const SizedBox(height: 20),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Expanded(child: buildBoard()),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }