import 'dart:math';
import 'package:flutter/material.dart';

void main() {
  runApp(const LudoApp());
  }

  class LudoApp extends StatelessWidget {
    const LudoApp({super.key});

      @override
        Widget build(BuildContext context) {
            return MaterialApp(
                  debugShowCheckedModeBanner: false,
                        theme: ThemeData.dark(),
                              home: const LudoBoard(),
                                  );
                                    }
                                    }

                                    class LudoBoard extends StatefulWidget {
                                      const LudoBoard({super.key});

                                        @override
                                          State<LudoBoard> createState() => _LudoBoardState();
                                          }

                                          class _LudoBoardState extends State<LudoBoard> {
                                            int dice = 1;
                                              int position = 0;

                                                final int totalCells = 52;

                                                  void rollDice() {
                                                      setState(() {
                                                            dice = Random().nextInt(6) + 1;
                                                                  position = (position + dice) % totalCells;
                                                                      });
                                                                        }

                                                                          @override
                                                                            Widget build(BuildContext context) {
                                                                                final double boardSize = MediaQuery.of(context).size.width - 40;
                                                                                    final double cellSize = boardSize / 15;

                                                                                        return Scaffold(
                                                                                              backgroundColor: Colors.black,
                                                                                                    body: Center(
                                                                                                            child: Column(
                                                                                                                      mainAxisAlignment: MainAxisAlignment.center,
                                                                                                                                children: [
                                                                                                                                            const Text(
                                                                                                                                                          "CA LUDO – The Board of Balance",
                                                                                                                                                                        style: TextStyle(fontSize: 22, fontWeight: FontWeight.bold),
                                                                                                                                                                                    ),
                                                                                                                                                                                                const SizedBox(height: 10),
                                                                                                                                                                                                            Text("🎲 Dice: $dice"),
                                                                                                                                                                                                                        const SizedBox(height: 20),

                                                                                                                                                                                                                                    // BOARD
                                                                                                                                                                                                                                                SizedBox(
                                                                                                                                                                                                                                                              width: boardSize,
                                                                                                                                                                                                                                                                            height: boardSize,
                                                                                                                                                                                                                                                                                          child: Stack(
                                                                                                                                                                                                                                                                                                          children: [
                                                                                                                                                                                                                                                                                                                            CustomPaint(
                                                                                                                                                                                                                                                                                                                                                size: Size(boardSize, boardSize),
                                                                                                                                                                                                                                                                                                                                                                    painter: LudoPainter(),
                                                                                                                                                                                                                                                                                                                                                                                      ),

                                                                                                                                                                                                                                                                                                                                                                                                        // TOKEN
                                                                                                                                                                                                                                                                                                                                                                                                                          AnimatedPositioned(
                                                                                                                                                                                                                                                                                                                                                                                                                                              duration: const Duration(milliseconds: 500),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  curve: Curves.easeInOut,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      left: (position % 15) * cellSize,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          top: (position ~/ 15) * cellSize,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              child: Container(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    width: cellSize,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          height: cellSize,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                decoration: BoxDecoration(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        color: Colors.yellow,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                borderRadius: BorderRadius.circular(20),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            child: const Center(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    child: Text("CA 🎓"),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ),

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const SizedBox(height: 20),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ElevatedButton(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onPressed: rollDice,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              child: const Text("ROLL AUDIT DICE 🎲"),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        class LudoPainter extends CustomPainter {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          @override
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            void paint(Canvas canvas, Size size) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                final paint = Paint()..color = Colors.grey.shade800;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    final cell = size.width / 15;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Draw grid
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            for (int i = 0; i < 15; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  for (int j = 0; j < 15; j++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if (i == 7 || j == 7) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    canvas.drawRect(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Rect.fromLTWH(i * cell, j * cell, cell, cell),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            paint,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Center home
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                final homePaint = Paint()..color = Colors.orange;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    canvas.drawRect(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Rect.fromLTWH(6 * cell, 6 * cell, 3 * cell, 3 * cell),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                homePaint,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        @override
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          bool shouldRepaint(covariant CustomPainter oldDelegate) => false;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }